# Generated by Django 2.1 on 2020-01-16 06:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(error_messages={'unique': '该条形码已存在，请重新输入或打开编辑功能！'}, max_length=20, unique=True, verbose_name='条形码')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gend', models.CharField(max_length=20, verbose_name='性别')),
                ('birt', models.DateField(null=True, verbose_name='出生日期')),
                ('uids', models.CharField(max_length=20, null=True, verbose_name='证件号码')),
                ('hist', models.CharField(max_length=20, null=True, verbose_name='现病史')),
                ('fami', models.CharField(max_length=20, null=True, verbose_name='家族病史')),
                ('diag', models.CharField(max_length=20, null=True, verbose_name='临床诊断')),
                ('styp', models.CharField(max_length=20, verbose_name='样本类型')),
                ('stat', models.CharField(max_length=20, verbose_name='样本状态')),
                ('smar', models.CharField(max_length=200, null=True, verbose_name='样本备注')),
                ('test', models.CharField(max_length=20, verbose_name='检测项目')),
                ('dcol', models.DateField(null=True, verbose_name='采样日期')),
                ('djoi', models.DateField(auto_now_add=True, verbose_name='收样日期')),
                ('unit', models.CharField(max_length=20, verbose_name='送检单位')),
                ('send', models.CharField(max_length=20, verbose_name='送检人')),
                ('phon', models.CharField(max_length=20, verbose_name='手机号码')),
                ('emai', models.CharField(max_length=20, null=True, verbose_name='电子邮箱')),
                ('rtyp', models.CharField(default='电子报告', max_length=20, verbose_name='报告类型')),
                ('rmar', models.CharField(max_length=200, null=True, verbose_name='备注信息')),
                ('isde', models.BooleanField(default=False, verbose_name='是否删除')),
                ('edit', models.DateField(auto_now=True, null=True, verbose_name='修改日期')),
                ('esta', models.CharField(default='未审核', max_length=20, null=True, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '样本管理',
                'db_table': 'sample',
                'ordering': ['id'],
            },
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
